# Build
name: build
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: rush install
              run: node common/scripts/install-run-rush.js install

            - name: build
              run: node common/scripts/install-run-rush.js build --to lib-with-dep-10
